name: fairchem
channels:
  - defaults
  - conda-forge
dependencies:
  - absl-py=2.1.0=py312hca03da5_0
  - aiodns=3.5.0=py312hca03da5_0
  - aiofiles=24.1.0=py312hca03da5_0
  - aiohappyeyeballs=2.6.1=py312hca03da5_0
  - aiohttp=3.12.15=py312h79febb2_0
  - aioitertools=0.12.0=py312hca03da5_0
  - aiosignal=1.4.0=py312hca03da5_0
  - annotated-types=0.6.0=py312hca03da5_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=4.10.0=py312hca03da5_0
  - aom=3.6.0=h313beb8_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - ase=3.26.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py312hca03da5_0
  - bcrypt=4.3.0=py312h2aea54e_0
  - bibtexparser=1.4.3=pyhd8ed1ab_0
  - blake3=1.0.8=py312h6ef9ec0_0
  - blas=1.0=openblas
  - blinker=1.9.0=py312hca03da5_0
  - boto3=1.37.10=py312hca03da5_0
  - botocore=1.37.10=py312hca03da5_0
  - bottleneck=1.4.2=py312ha86b861_0
  - brotlicffi=1.0.9.2=py312h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.11.4=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py312hca03da5_0
  - cffi=2.0.0=py312h3a083c1_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py312hca03da5_0
  - cloudpickle=3.1.1=py312hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py312h48ca7d4_0
  - cpython=3.12.11=py312hd8ed1ab_0
  - cryptography=46.0.2=py312h108b7f8_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.17=py312h56d30c9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dnspython=2.4.2=py312hca03da5_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - e3nn=0.5.8=pyhd8ed1ab_0
  - emmet-core=0.85.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=py312hca03da5_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fairchem-core=1.10.0=pyhd8ed1ab_0
  - fastapi=0.116.1=py312hca03da5_0
  - filelock=3.17.0=py312hca03da5_0
  - flask=3.1.2=py312hca03da5_0
  - fontconfig=2.15.0=h1383a14_1
  - fonttools=4.60.1=py312h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - frozenlist=1.5.0=py312h80987f9_0
  - fsspec=2025.7.0=py312hd096484_0
  - future=1.0.0=py312hca03da5_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gitdb=4.0.12=py312hca03da5_0
  - gitpython=3.1.43=py312hca03da5_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py312h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - grpcio=1.68.2=py312he4e58e5_0
  - h11=0.16.0=py312hca03da5_0
  - harfbuzz=10.4.0=hb72c1af_0
  - hf-xet=1.1.8=py312h8cd5084_0
  - huggingface_hub=0.34.4=py312hca03da5_0
  - hydra-core=1.3.2=pyhd8ed1ab_1
  - icu=75.1=hfee45f7_0
  - idna=3.7=py312hca03da5_0
  - importlib-metadata=8.5.0=py312hca03da5_0
  - importlib-resources=6.5.2=pyhd3eb1b0_0
  - importlib_resources=6.5.2=py312hca03da5_0
  - ipykernel=7.0.1=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - itsdangerous=2.2.0=py312hca03da5_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py312hca03da5_0
  - jmespath=1.0.1=py312hca03da5_0
  - joblib=1.5.2=py312hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jsonlines=4.0.0=py312hca03da5_0
  - jsonschema=4.25.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.8=py312h313beb8_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20240722.0=cxx17_h07bc746_4
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libavif=1.1.1=h80987f9_0
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libcblas=3.9.0=1_h9886b1c_netlib
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.2=hdc2269c_0
  - libgrpc=1.68.2=h0a426d6_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - liblapack=3.9.0=1_h9886b1c_netlib
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=hf2bb037_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=5.28.3=h3bd63a1_1
  - libre2-11=2024.07.02=h07bc746_2
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.0=h91aec0a_0
  - libtorch=2.4.1=cpu_generic_h4e0ee09_6
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.15.0=h9329255_1
  - libxml2-16=2.15.0=h0ff4647_1
  - libxslt=1.1.43=hb2570ba_1
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.44.0=py312heb35c27_1
  - lmdb=0.9.31=h79febb2_0
  - lxml=6.0.2=py312h447b5cf_1
  - lz4-c=1.9.4=h313beb8_1
  - maggma=0.72.0=pyhd8ed1ab_0
  - markdown=3.8=py312hca03da5_0
  - markupsafe=3.0.2=py312h80987f9_0
  - matminer=0.9.3=pyhd8ed1ab_1
  - matplotlib-base=3.10.6=py312h066045a_0
  - mongogrant=0.3.3=pyhd8ed1ab_1
  - mongomock=4.3.0=pyhd8ed1ab_0
  - monty=2025.3.3=pyhd8ed1ab_0
  - mp-api=0.45.12=pyhd8ed1ab_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py312hca03da5_0
  - msgpack-python=1.1.1=py312h313beb8_0
  - multidict=6.1.0=py312h80987f9_0
  - mypy_extensions=1.0.0=py312hca03da5_0
  - narwhals=2.7.0=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - networkx=3.5=py312hca03da5_0
  - nomkl=3.0=0
  - numba=0.61.2=py312h32e2601_0
  - numexpr=2.11.0=py312h8c72970_1
  - numpy=1.26.4=py312h901140f_1
  - numpy-base=1.26.4=py312hae06d03_1
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.2=hba36e21_1
  - openpyxl=3.1.5=py312h80987f9_0
  - openssl=3.6.0=h5503f6c_0
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - opt_einsum_fx=0.1.4=pyhd8ed1ab_1
  - orjson=3.10.14=py312h2aea54e_0
  - packaging=25.0=py312hca03da5_0
  - palettable=3.3.3=py312hca03da5_0
  - pandas=2.3.3=py312hc6ded6b_0
  - paramiko=3.5.0=py312hca03da5_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312h6dd570d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.3.7=py312hca03da5_0
  - plotly=6.3.0=py312hd096484_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h80987f9_0
  - protobuf=5.28.3=py312hd8f9ff3_0
  - psutil=7.0.0=py312h254cc4a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybtex=0.25.1=pyhd8ed1ab_0
  - pycares=4.10.0=py312h091efcb_0
  - pycparser=2.23=py312hca03da5_0
  - pydantic=2.11.9=py312hca03da5_0
  - pydantic-core=2.33.2=py312h5e3a92f_0
  - pydantic-settings=2.10.1=py312hca03da5_0
  - pydash=8.0.5=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymatgen=2025.10.7=py312ha11c99a_0
  - pymatgen-io-validation=0.1.2=pyhd8ed1ab_0
  - pymongo=4.8.0=py312h80987f9_0
  - pynacl=1.6.0=py312h8ceae07_0
  - pyparsing=3.2.0=py312hca03da5_0
  - pyre-extensions=0.0.32=pyhd8ed1ab_1
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.11=hc22306f_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-dotenv=1.1.0=py312hca03da5_0
  - python-lmdb=1.6.2=py312h313beb8_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-wget=3.2=py_0
  - python_abi=3.12=1_cp312
  - pytorch=2.4.1=cpu_generic_py312_h8687a0b_6
  - pytorch_geometric=2.6.1=pyhecae5ae_2
  - pytorch_scatter=2.1.2=cpu_py312h3e85fa5_8
  - pytz=2025.2=py312hca03da5_0
  - pyyaml=6.0.2=py312h80987f9_0
  - pyzmq=27.1.0=py312h854a7ef_0
  - re2=2024.07.02=h6589ca4_2
  - readline=8.3=h0b18652_0
  - referencing=0.30.2=py312hca03da5_0
  - requests=2.32.5=py312hca03da5_0
  - rpds-py=0.22.3=py312h2aea54e_0
  - ruamel.yaml=0.18.10=py312h80987f9_0
  - ruamel.yaml.clib=0.2.12=py312h80987f9_0
  - s3transfer=0.11.2=py312hca03da5_0
  - scikit-learn=1.7.2=py312hc6ded6b_0
  - scipy=1.16.2=py312h53ebd84_0
  - sentinels=1.0.0=py_1
  - sentry-sdk=2.18.0=py312hca03da5_0
  - setproctitle=1.3.6=py312h79febb2_0
  - setuptools=80.9.0=py312hca03da5_0
  - six=1.17.0=py312hca03da5_0
  - sleef=3.9.0=hb028509_0
  - smart-open=7.3.1=h08b120a_0
  - smart_open=7.3.1=pyhcf101f3_0
  - smmap=5.0.2=py312hca03da5_0
  - sniffio=1.3.0=py312hca03da5_0
  - spglib=2.6.0=py312h3daaf81_0
  - sshtunnel=0.4.0=hd3eb1b0_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.47.3=py312hca03da5_0
  - submitit=1.5.2=pyhd8ed1ab_0
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=py312hca03da5_0
  - tbb=2021.8.0=h48ca7d4_0
  - tensorboard=2.19.0=py312hca03da5_0
  - tensorboard-data-server=0.7.0=py312ha6e5c4f_1
  - threadpoolctl=3.5.0=py312h989b03a_0
  - tk=8.6.15=hcd8a7d5_0
  - torch-geometric=2.6.1=pyhd8ed1ab_0
  - torchsnapshot=0.1.0=pyhd8ed1ab_1
  - torchtnt=0.2.4=pyhd8ed1ab_1
  - tornado=6.5.2=py312h163523d_1
  - tqdm=4.67.1=py312h989b03a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing=3.10.0.0=py312hca03da5_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing-inspection=0.4.0=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - typing_inspect=0.9.0=py312hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - urllib3=2.5.0=py312hca03da5_0
  - uvicorn=0.35.0=py312hca03da5_0
  - uvloop=0.21.0=py312h80987f9_0
  - wandb=0.22.2=py312h7a0e18e_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=py312hca03da5_0
  - wheel=0.45.1=py312hca03da5_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wrapt=1.17.0=py312h80987f9_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.18.0=py312h80987f9_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.21.0=py312hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - autopep8==2.3.2
      - matplotlib-inline==0.1.7
      - pycodestyle==2.14.0
prefix: /Users/hliu/miniconda3/envs/fairchem
